# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, username, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules =  ["nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
  #
    { device = "/dev/disk/by-uuid/55630adc-8e93-4be7-bb04-eba5971976eb";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };
#
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E1C6-44FF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/home/${username}/SSD_Drive" =
      {
        device = "/dev/disk/by-uuid/2453FDDB351A8F72";
        fsType = "ntfs";
        options = [
          "users"
          "nofail"
          "exec"
          "uid=1000" # Your user ID (run 'id -u' to find it)
          "gid=100"  # Your group ID (run 'id -g' or use 'users' for common group)
          "fmask=0022" # File permissions (example: full read/write for owner)
          "dmask=0022" # Directory permissions
        ];
      };

  swapDevices =
  #
    [ { device = "/dev/disk/by-uuid/e9c3439b-a0e2-4d1a-93d8-05f342a3e1e0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
