{ lib, ... }:
{
  wayland.windowManager.hyprland.settings = {
    bindd = [
      "$mainMod, D, all launcher, exec, noctalia-shell ipc call launcher toggle"
      "$mainMod, B, open default browser, exec, xdg-open \"https://\""
      "$mainMod, A, desktop overview, exec, nix-OverviewToggle"
      "$mainMod, Return, Open terminal, exec, $term"
      "$mainMod, E, file manager, exec, $files"
      "$mainMod, H, help / cheat sheet, exec, nix-KeyHints"
      "$mainMod ALT, E, emoji menu, exec, $scriptsDir/RofiEmoji.sh"
      "$mainMod, S, web search, exec, nix-RofiSearch"
      "$mainMod CTRL, S, window switcher, exec, rofi -show window"
      "$mainMod SHIFT, G, toggle game mode, exec, $scriptsDir/GameMode.sh"
      "$mainMod ALT, L, toggle master/dwindle layout, exec, $scriptsDir/ChangeLayout.sh"
      "$mainMod ALT, V, clipboard manager, exec, $scriptsDir/ClipManager.sh"
      "$mainMod CTRL, R, rofi theme selector, exec, nix-RofiThemeSelector"
      "$mainMod SHIFT, F, fullscreen, fullscreen"
      "$mainMod CTRL, F, maximize window, fullscreen, 1"
      "$mainMod, SPACE, Float current window, togglefloating,"
      "$mainMod ALT, SPACE, Float all windows, exec, hyprctl dispatch workspaceopt allfloat"
      "$mainMod SHIFT, Return, DropDown terminal, togglespecialworkspace, term"
      "$mainMod ALT, mouse_down, zoom in, exec, hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')\""
      "$mainMod ALT, mouse_up, zoom out, exec, hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')\""
      "$mainMod CTRL ALT, B,toggle bar, exec, noctalia-shell ipc call bar toggle"
      "$mainMod SHIFT, M, online music, togglespecialworkspace, music"
      "$mainMod SHIFT, B, bitwarden scratchpad, togglespecialworkspace, bitwarden"
      "$mainMod, W, select wallpaper, exec, noctalia-shell ipc call wallpaper toggle"
      "CTRL ALT, W, random wallpaper, exec, noctalia-shell ipc call wallpaper random"
      "$mainMod CTRL, O, toggle active window opacity, exec, hyprctl setprop active opaque toggle"
      "$mainMod SHIFT, K, search keybinds, exec, nix-KeyBinds"
      "$mainMod SHIFT, A, animations menu, exec, $scriptsDir/Animations.sh"
      "$mainMod SHIFT, O, change oh-my-zsh theme, exec, nix-ZshChangeTheme"
      "$mainMod ALT, C, calculator, exec, nix-RofiCalc"
      "$mainMod CTRL, F9, move workspace to left monitor, movecurrentworkspacetomonitor, l"
      "$mainMod CTRL, F10, move workspace to right monitor, movecurrentworkspacetomonitor, r"
      "$mainMod CTRL, F11, move workspace to up monitor, movecurrentworkspacetomonitor, u"
      "$mainMod CTRL, F12, move workspace to down monitor, movecurrentworkspacetomonitor, d"
      "CTRL ALT, Delete, exit Hyprland, exec, hyprctl dispatch exit 0"
      "$mainMod, Q, close active window, killactive,"
      "$mainMod SHIFT, Q, Terminate active process, exec, nix-KillActiveProcess"
      "CTRL ALT, L, lock screen, exec, noctalia-shell ipc call lockScreen lock"
      "CTRL ALT, P, powermenu, exec, noctalia-shell ipc call sessionMenu toggle"
      "$mainMod SHIFT, N, notification panel, exec, noctalia-shell ipc call notifications toggleHistory"
      "$mainMod SHIFT, E, Quick settings menu, exec, nix-Kool_Quick_Settings"
      "$mainMod CTRL, D, remove master, layoutmsg, removemaster"
      "$mainMod, I, add master, layoutmsg, addmaster"
      "$mainMod CTRL, Return, swap with master, layoutmsg, swapwithmaster"
     # "$mainMod SHIFT, I, layoutmsg, togglesplit"
     # "$mainMod, P, layoutmsg, pseudo,"
      "$mainMod, M, set split ratio 0.3, exec, hyprctl dispatch splitratio 0.3"
      "ALT, tab, cycle next window, cyclenext"
      "ALT, tab, bring active to top, bringactivetotop"
      "$mainMod, Print, screenshot now, exec, nix-ScreenShot --now"
      "$mainMod SHIFT, Print, screenshot (area), exec, nix-ScreenShot --area"
      "$mainMod CTRL, Print, screenshot in 5s, exec, nix-ScreenShot --in5"
      "$mainMod CTRL SHIFT, Print, screenshot in 10s, exec, nix-ScreenShot --in10"
      "ALT, Print, screenshot active window, exec, nix-ScreenShot --active"
      "$mainMod SHIFT, S, screenshot (swappy), exec, nix-ScreenShot --swappy"
      "$mainMod CTRL, left, move window left, movewindow, l"
      "$mainMod CTRL, right, move window right, movewindow, r"
      "$mainMod CTRL, up, move window up, movewindow, u"
      "$mainMod CTRL, down, move window down, movewindow, d"
      "$mainMod ALT, left, swap window left, swapwindow, l"
      "$mainMod ALT, right, swap window right, swapwindow, r"
      "$mainMod ALT, up, swap window up, swapwindow, u"
      "$mainMod ALT, down, swap window down, swapwindow, d"
      "$mainMod, G, toggle group, togglegroup"
      "$mainMod, Tab, Change Group Forward, changegroupactive, f"
      "$mainMod CTRL, tab, change active in group, changegroupactive"
      "$mainMod SHIFT, Tab, Change Group Back, changegroupactive, b"
      "$mainMod CTRL, K, Move left into group, moveintogroup, l"
      "$mainMod CTRL, L, Move Right into group, moveintogroup, r"
      "$mainMod CTRL, H, Move active out of group, moveoutofgroup"
      "$mainMod, left, focus left, movefocus, l"
      "$mainMod, right, focus right, movefocus, r"
      "$mainMod, up, focus up, movefocus, u"
      "$mainMod, down, focus down, movefocus, d"
      "$mainMod, tab, next workspace, workspace, m+1"
      "$mainMod SHIFT, tab, previous workspace, workspace, m-1"
      "$mainMod SHIFT, U, move to special workspace, movetoworkspace, special"
      "$mainMod, U, toggle special workspace, togglespecialworkspace,"
      "$mainMod, code:10, workspace 1, workspace, 1"
      "$mainMod, code:11, workspace 2, workspace, 2"
      "$mainMod, code:12, workspace 3, workspace, 3"
      "$mainMod, code:13, workspace 4, workspace, 4"
      "$mainMod, code:14, workspace 5, workspace, 5"
      "$mainMod, code:15, workspace 6, workspace, 6"
      "$mainMod, code:16, workspace 7, workspace, 7"
      "$mainMod, code:17, workspace 8, workspace, 8"
      "$mainMod, code:18, workspace 9, workspace, 9"
      "$mainMod, code:19, workspace 10, workspace, 10"
      "$mainMod SHIFT, code:10, move to workspace 1, movetoworkspace, 1"
      "$mainMod SHIFT, code:11, move to workspace 2, movetoworkspace, 2"
      "$mainMod SHIFT, code:12, move to workspace 3, movetoworkspace, 3"
      "$mainMod SHIFT, code:13, move to workspace 4, movetoworkspace, 4"
      "$mainMod SHIFT, code:14, move to workspace 5, movetoworkspace, 5"
      "$mainMod SHIFT, code:15, move to workspace 6, movetoworkspace, 6"
      "$mainMod SHIFT, code:16, move to workspace 7, movetoworkspace, 7"
      "$mainMod SHIFT, code:17, move to workspace 8, movetoworkspace, 8"
      "$mainMod SHIFT, code:18, move to workspace 9, movetoworkspace, 9"
      "$mainMod SHIFT, code:19, move to workspace 10, movetoworkspace, 10"
      "$mainMod SHIFT, bracketleft, move to previous workspace, movetoworkspace, -1"
      "$mainMod SHIFT, bracketright, move to next workspace, movetoworkspace, +1"
      "$mainMod CTRL, code:10, move silently to workspace 1, movetoworkspacesilent, 1"
      "$mainMod CTRL, code:11, move silently to workspace 2, movetoworkspacesilent, 2"
      "$mainMod CTRL, code:12, move silently to workspace 3, movetoworkspacesilent, 3"
      "$mainMod CTRL, code:13, move silently to workspace 4, movetoworkspacesilent, 4"
      "$mainMod CTRL, code:14, move silently to workspace 5, movetoworkspacesilent, 5"
      "$mainMod CTRL, code:15, move silently to workspace 6, movetoworkspacesilent, 6"
      "$mainMod CTRL, code:16, move silently to workspace 7, movetoworkspacesilent, 7"
      "$mainMod CTRL, code:17, move silently to workspace 8, movetoworkspacesilent, 8"
      "$mainMod CTRL, code:18, move silently to workspace 9, movetoworkspacesilent, 9"
      "$mainMod CTRL, code:19, move silently to workspace 10, movetoworkspacesilent, 10"
      "$mainMod CTRL, bracketleft, move silently to previous workspace, movetoworkspacesilent, -1"
      "$mainMod CTRL, bracketright, move silently to next workspace, movetoworkspacesilent, +1"
      "$mainMod, mouse_down, next workspace, workspace, e+1"
      "$mainMod, mouse_up, previous workspace, workspace, e-1"
      "$mainMod, period, next workspace, workspace, e+1"
      "$mainMod, comma, previous workspace, workspace, e-1"
    ];
    bind = [
      "$mainMod, R, exec, killall -SIGUSR1 gpu-screen-recorder"
      ", xf86Launch1, exec, rog-control-center"
      ", xf86Launch3, exec, asusctl led-mode -n"
      ", xf86Launch4, exec, asusctl profile -n"
      ", xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh"
      "$mainMod, F6, exec, $scriptsDir/ScreenShot.sh --now"
      "$mainMod SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area"
      "$mainMod CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5"
      "$mainMod ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10"
      "ALT, F6, exec, $scriptsDir/ScreenShot.sh --active"
    ];
    bindlnd = [
      "ALT_L, SHIFT_L, switch keyboard layout globally, exec, nix-SwitchKeyboardLayout"
    ];
    bindeld = [
      ", xf86audioraisevolume, volume up, exec, noctalia-shell ipc call volume increase"
      ", xf86audiolowervolume, volume down, exec, noctalia-shell ipc call volume decrease"
    ];
    bindld = [
      ", xf86AudioMicMute, toggle mic mute, exec, noctalia-shell ipc call volume muteInput"
      ", xf86audiomute, toggle mute, exec, noctalia-shell ipc call volume muteOutput"
      ", xf86AudioPlay, play, exec, noctalia-shell ipc call media playPause"
      ", xf86AudioNext, next track, exec, noctalia-shell ipc call media next"
      ", xf86AudioPrev, previous track, exec, noctalia-shell ipc call media previous"
      ", xf86audiostop, stop, exec, nix-MediaCtrl --stop"
    ];
    binded = [
      "$mainMod SHIFT, left, resize left (-50), resizeactive, -50 0"
      "$mainMod SHIFT, right, resize right (+50), resizeactive, 50 0"
      "$mainMod SHIFT, up, resize up (-50), resizeactive, 0 -50"
      "$mainMod SHIFT, down, resize down (+50), resizeactive, 0 50"
    ];
    bindmd = [
      "$mainMod, mouse:272, move window, movewindow"
      "$mainMod, mouse:273, resize window, resizewindow"
    ];
    binde = [
      ", xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec"
      ", xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc"
      ", xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec"
      ", xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc"
    ];
  };
}
